### ISSUE TITLE
UTF-8 decode problems when using en_US

### ISSUE THREAD

**Issue by fsoderblom** [fredrik-eriksson/pwgen#1]
Works fine with sv_SE, but not with en_US.

```bash
$ /usr/local/bin/pwgen --lang sv_SE
Generated 5 passwords
Full-knowledge entropy is 93
Blind entropy	Password
========================
230.32		Spöstraffen.trakégälar.Omspinns.langnings/WXZ.56:
262.37		Marstrandsbon_altargångarnas_börsanalytikerna_Kulbanan_62:
194.51		Förlägrens.framträdandet.påsiktens.avs..52,
227.43		Kinarosors_Rännandet_Flygbomberna_mensrelaterat_49/
230.7		Födandet=Gomorra=efterhärmningars=Drakdräkterna=30:
========================

$ /usr/local/bin/pwgen
Traceback (most recent call last):
  File "/usr/local/bin/pwgen", line 4, in <module>
    __import__('pkg_resources').run_script('pwgen==0.1', 'pwgen')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/pwgen-0.1-py3.5.egg/EGG-INFO/scripts/pwgen", line 115, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pwgen-0.1-py3.5.egg/EGG-INFO/scripts/pwgen", line 101, in main
  File "/usr/local/lib/python3.5/dist-packages/pwgen-0.1-py3.5.egg/pwgen/__init__.py", line 161, in generate_passwords
  File "/usr/local/lib/python3.5/dist-packages/pwgen-0.1-py3.5.egg/pwgen/__init__.py", line 109, in _read_dictionary
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 6: invalid continuation byte
```

**Comment by fredrik-eriksson** [comment]
Hi, and thanks for showing interest :)
I can't reproduce this; it works fine for me; could you provide links to the .dic and .aff file you're using?

It might also be useful to test with a newer python release. The oldest one I've used it with for a while is 3.6.

**Comment by fsoderblom** [comment]
Sure, I'm using the standard hunspell-en-us from Ubuntu 16.04 LTS:

```bash
# dpkg -l hunspell-en-us
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-==================================================
ii  hunspell-en-us         20070829-6ubuntu all              English_american dictionary for hunspell
```

I'll try to reproduce it with a newer python as well, stay tuned :P
